### ISSUE TITLE
Not filtering the users

### ISSUE THREAD

**Issue by NejmeddineR** [silentrobi/keycloak-custom-api-searchby-attr#1]
Hi, 

So I cloned the project and ran mvn clean install and i had this error:
Compilation failure
keycloak-custom-api-searchby-attr-master/src/main/java/keycloak/apiextension/KeyCloakUserApiProviderFactory.java:[3,29] cannot find symbol
[ERROR]   symbol:   class TokenKeyCloakUserApiProvider
[ERROR]   location: package keycloak.apiextension

So I went and changed the import to .* and ran it again. This time it worked but it keeps returning the list of all the users of the realm. 

Keycloak is telling me that the jar file has been deployed.

I'm using keycloak 12.0.4 and maven 3.6.3 and using this query url with postman:
localhost:9990/auth/admin/realms/myrealm/users?attr=merchant_id&value=1

The query url mentioned in the workshop is not working.

If i'm doing something wrong please let me know. If not I hope you fix this as soon as possible as I need it for my graduation project.

**Comment by silentrobi** [comment]
Hey I've fixed the import issue. It should work now.
**Sample URL:** `<host>/auth/realms/<realm name>/userapi-rest/users/search-by-attr?attr=merchant_id&value=1`

**Comment by NejmeddineR** [comment]
Thank you very much! it is working now
